{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8533f974",
   "metadata": {},
   "source": [
    "Q1- Why are functions advantageous to have in your programs?\n",
    "ANS-\n",
    "\n",
    "1-Reusability: Functions allow you to write a block of code that can be used multiple times throughout your program without having to rewrite the code each time. This makes your code more efficient and easier to maintain.\n",
    "\n",
    "2-Modularity: Functions allow you to break down a large program into smaller, more manageable modules. This makes your code easier to read and understand, and it also makes it easier to debug.\n",
    "\n",
    "3-Abstraction: Functions provide a level of abstraction, which means that you can use a function without having to understand how it works internally. This allows you to focus on the high-level functionality of your program, rather than the details of how it is implemented.\n",
    "\n",
    "4-Encapsulation: Functions can encapsulate code and data, which means that they can hide implementation details and prevent other parts of your program from accessing them. This improves security and reduces the risk of errors and bugs.\n",
    "\n",
    "5-Testing: Functions make it easier to test your code, since you can test each function in isolation before integrating it into the larger program. This helps you to catch errors and bugs early on, when they are easier to fix."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d864fe94",
   "metadata": {},
   "source": [
    "Q2-When does the code in a function run: when its specified or when its called?\n",
    "ANS-\n",
    "\n",
    "The code in a function runs when it is called, not when it is specified.\n",
    "When you define a function, you are essentially creating a block of code that performs a specific task or set of tasks and giving it a name that can be used to call the function later. The code inside the function is not executed at the time of definition. Instead, the code is stored in memory, and the function is registered as a callable object.\n",
    "\n",
    "When the function is called, either by the main program or by another function, the code inside the function is executed. The function takes any input arguments that were passed to it, performs its designated task, and then returns any output values that were generated by the code."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "747a034e",
   "metadata": {},
   "source": [
    "Q3-What statement creates a function?\n",
    "ANS-\n",
    "\n",
    "The \"def\" statement is used to create a function."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b64a9667",
   "metadata": {},
   "source": [
    "Q4-What is the difference between a function and a function call?\n",
    "ANS-\n",
    "\n",
    "A function is a block of code that performs a specific task or set of tasks. It is defined using the def keyword in Python, and can take zero or more input parameters and return zero or more output values.\n",
    "\n",
    "On the other hand, a function call is an instruction that tells the program to execute a specific function with a given set of input parameters. When a function is called, the program jumps to the function definition, executes the code block inside it, and then returns to the point in the program where the function was call"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ce6782e7",
   "metadata": {},
   "source": [
    "Q5-How many global scopes are there in a Python program? How many local scopes?\n",
    "ANS-\n",
    "\n",
    "There is only one global scope, which is created when the program starts executing. The global scope is the highest level of the program's namespace hierarchy, and any variables defined in this scope are accessible from any part of the program, including from within functions.\n",
    "\n",
    "On the other hand, there can be multiple local scopes in a Python program. A local scope is created whenever a function is called, and it exists only for the duration of that function call. Any variables defined within a function are only accessible within that function and its nested functions. Once the function call completes, the local scope is destroyed, and any variables defined within it are lost.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a215b3e6",
   "metadata": {},
   "source": [
    "Q6-What happens to variables in a local scope when the function call returns?\n",
    "ANS-\n",
    "\n",
    "When a function call returns, any variables defined within the local scope of that function are destroyed. This means that they are no longer accessible from any part of the program, and their values are lost."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "160549df",
   "metadata": {},
   "source": [
    "Q7-What is the concept of a return value? Is it possible to have a return value in an expression?\n",
    "ANS-\n",
    "A return value is the value that a function sends back to the caller after it completes its execution. When a function is called, it can perform some operations and return a value back to the calling code. The return value can be of any data type - it can be a number, a string, a list, a tuple, a dictionary, or even another function.\n",
    "If the return statement is not followed by an expression, the function returns None by default"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "572bf8fe",
   "metadata": {},
   "source": [
    "Q8-If a function does not have a return statement, what is the return value of a call to that function?\n",
    "ANS-\n",
    "\n",
    "If a function does not have a return statement, the return value of a call to that function will be None. This is because in Python, a function without a return statement implicitly returns \"None\" at the end of its execution."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f57e8ea6",
   "metadata": {},
   "source": [
    "Q9-How do you make a function variable refer to the global variable?\n",
    "ANS-\n",
    "\n",
    "you can use the \"global\" keyword to declare that a variable inside a function refers to a global variable with the same name. This allows you to modify the value of the global variable from within the function."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d23e2dd8",
   "metadata": {},
   "source": [
    "Q10-What is the data type of None?\n",
    "ANS-\n",
    "\n",
    "The data type of None is NoneType"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a241f07b",
   "metadata": {},
   "source": [
    "Q11-What does the sentence import areallyourpetsnamederic do?\n",
    "ANS-\n",
    "\n",
    "The sentence import areallyourpetsnamederic is not a valid Python statement and would raise a ModuleNotFoundError"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1025d688",
   "metadata": {},
   "source": [
    "Q12-If you had a bacon() feature in a spam module, what would you call it after importing spam?\n",
    "ANS-\n",
    "\n",
    "bacon() function is defined within the spam module, you could call it after importing spam by using the dot notation to access the function"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4229a825",
   "metadata": {},
   "source": [
    "Q13-What can you do to save a programme from crashing if it encounters an error?\n",
    "ANS-\n",
    "\n",
    "1-Use exception handling\n",
    "\n",
    "2-Validate input\n",
    "\n",
    "3-Use defensive programming\n",
    "\n",
    "4-Use third-party libraries"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "55971dcd",
   "metadata": {},
   "source": [
    "Q14-What is the purpose of the try clause? What is the purpose of the except clause?\n",
    "ANS-\n",
    "\n",
    "The purpose of the try clause is to attempt to execute a block of code that might raise an exception. The code within the try block is executed until an exception is encountered or until the block of code completes without raising an exception. If an exception is raised, the code execution within the try block stops, and the control is transferred to the except block.\n",
    "\n",
    "The purpose of the except clause is to handle the exception that was raised within the try block. The code within the except block is executed only if an exception occurs in the try block. You can use the except clause to catch the exception and take appropriate action, such as logging an error message, retrying the code block, or handling the exception in some other way."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
